### ISSUE TITLE
How to ensure always dispose formstate when necessary

### ISSUE THREAD

**Issue by lzfee0227** [qiniu/formstate-x#18]
sth like:

```ts
new FormState(initValue, disposer)
```

or

https://github.com/mobxjs/mobx-react/issues/561

or sth else

FYI:

https://mobx.js.org/best/pitfalls.html#always-dispose-reactions

**Comment by nighca** [comment]
It can be another question: in which cases should we dispose `FormState` / `FieldState`?

**Comment by lzfee0227** [comment]
> https://mobx.js.org/best/pitfalls.html#always-dispose-reactions

> It can be another question: in which cases should we dispose `FormState` / `FieldState`?

![image](https://user-images.githubusercontent.com/1984045/75776675-62f2b080-5d8f-11ea-99f6-33dac4d91e26.png)

case: use global store in validators? (will use autorun in formstate-x)

@nighca

**Comment by nighca** [comment]
> case: use global store in validators? 

And in the predict function of `disableValidationWhen`.

**Comment by nighca** [comment]
With change of v3.x—as we stated in #40

> https://github.com/qiniu/formstate-x/issues/18 will partly benefit from this: fields of array form state will always be correctly disposed as we manipulate them inside of formstate-x only.

We no longer need to worry about `dispose` for child states. The remaining problem is: how to ensure the root state correctly disposed.

Actually it is almost the same problem as: how to ensure a MobX store correctly disposed.

Just like the latter one mostly solved with tools like [`useLocalStore`](https://github.com/qbox/fe-core/blob/8ef6b7e783d7813e18f3e54bb2c9be266d167770/local-store/index.ts#L146-L165), the previous one can be mostly solved with tools like [`useFormstateX`](https://github.com/qbox/horn/blob/6835b50336a85e6b0510137734943003891a5ffa/react-icecream/src/form-x/Form.tsx#L31-L67)

**Comment by nighca** [comment]
> Actually it is almost the same problem as: how to ensure a MobX store correctly disposed.

Since it turns out to be a problem not about formstate-x, but about MobX store. I will close this issue.
