### ISSUE TITLE
First validate() call runs validator function twice

### ISSUE THREAD

**Issue by mattleonowicz** [qiniu/formstate-x#94]
I have noticed this bug, that first `validate()` call runs all the validator functions twice.
Here is the simplest minimum reproducible example: https://codesandbox.io/p/sandbox/nice-fast-3vs9wy

I noticed because I started using async validators that call server and noticed double requests in the network.
My use case is that sometimes I need to create a form with initial values and immediately validate it.

**Comment by nighca** [comment]
Nice catch!

**Comment by nighca** [comment]
Fixed in [v3.1.2](https://github.com/qiniu/formstate-x/releases/tag/v3.1.2)
